version: "3"

services:
  db:
    image: postgres:9.6.16-alpine
    container_name: psql-db
    environment:
      POSTGRES_USER: 'gio'
      POSTGRES_PASSWORD: 'testing123'
      POSTGRES_DB: 'my_db'
    ports:
      - 15432:5432
  server:
    depends_on:
      - db
    image: parlezvous/server
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./migrations:/usr/app/migrations
      - ./src:/usr/app/src
    ports:
      - 3000:3000
