# TODO: learn how to reuse parts of a config yaml file to reduce
#       code duplication
#       i.e. restoring caches / workspaces

version: 2
jobs:
  install_deps:
    docker:
      - image: parlezvous/ci-base:0.5.0
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            echo "Node version: $(node -v)"
            echo "npm version: $(npm -v)"
            npm install

      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  typecheck:
    docker:
      - image: parlezvous/ci-base:0.5.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      
      - run:
          name: "TypeCheck"
          command: npm run typecheck
      
  lint:
    docker:
      - image: parlezvous/ci-base:0.5.0
    steps:
      - checkout
      - attach_workspace:
          at: .

      - run:
          name: "Linting"
          command: npm run lint

  test:
    docker:
      - image: parlezvous/ci-base:0.5.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: "Testing"
          command: npm run test

  migrate:
    docker:
      - image: parlezvous/ci-base:0.5.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: "Deploy Changes To Prisma Server"
          command: DEBUG="*" npx prisma migrate up --experimental

  deploy:
    docker:
      - image: parlezvous/ci-base:0.5.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: "Deploy Server"
          # Generate app.yaml for GAE
          # logs into gcloud
          # deploys to GAE
          command: |
            python generate-app-yaml.py > app.yaml
            echo $GCLOUD_SERVICE_ACCOUNT_KEY_FILE | base64 --decode > key.json
            gcloud auth activate-service-account --key-file=./key.json --project=$GCLOUD_PROJECT_ID
            gcloud app deploy --quiet

workflows:
  version: 2
  main:
    jobs:
      - install_deps
      - typecheck:
          requires:
            - install_deps
      - lint:
          requires:
            - install_deps
      - test:
          requires:
            - install_deps
      - migrate:
          filters:
            branches:
              only: master
          requires:
            - typecheck
            - lint
            - test
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - migrate
